[[repos]]
repo = "https://github.com/commitizen-tools/commitizen"
rev = "v4.16.3"
hooks = [
  { id = "commitizen" },
  { id = "commitizen-branch" },
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.17"
hooks = [
  { id = "ruff-check", args = ["--fix"] },
  { id = "ruff-format" },
]